### PR TITLE
Updating author tag and header of Config

### PR DESCRIPTION
**Pull request by keilw**
Credit for updated method signature and suggestions from https://github.com/microprofile/microprofile-config/issues/7
Also added 2017 as current year to header.

### CODE REVIEW

**Comment by keilw** [comment]
@Emily-Jiang Did you have a chance to look up this PR?

**Comment by Emily-Jiang** [comment]
@struberg said he would handle this.

**Comment by keilw** [comment]
I don't think he'd do based on his undemocratic and erratic behavior (also on the list e.g. when it comes to package naming etc.) but based on author credits for input and comments he made earlier in the same class, it is fair and reasonable to list everyone who made a structural change like https://github.com/microprofile/microprofile-config/issues/7

**Comment by keilw** [comment]
Beside although you're not listed in https://projects.eclipse.org/projects/technology.microprofile/who right now, IBM is in more than one way. So merging or pushing seems fine. No idea if @struberg is currently allowed to merge or push to an Eclipse project. He said he had been committer to Aether, but https://github.com/eclipse/aether-core and all the other Aether repos never showed a trace of his contribution since 2011. So I don't know,  if either Eclipse committer agreement or the new ECA exist for him, otherwise even if he did merge a PR it would be rejected by Eclipse IP.

**Comment by keilw** [comment]
I do have a legitimate Eclipse committer account and contribute to at least 3 projects. Most significantly UOMo https://github.com/eclipse/uomo/graphs/contributors with nearly 100k lines of code I pushed.

**Comment by keilw** [comment]
Take a simple example of an IBM-led Eclipse project like JDT:
https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.compiler.tool/src/org/eclipse/jdt/internal/compiler/tool/Options.java

 * Contributors:
 *     IBM Corporation - initial API and implementation
 *     Jesper Steen Moeller - Contributions for:
 *         Bug 407297: [1.8][compiler] Control generation of parameter names by option

So in the case of Config, it should have a similar history like
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *     Werner Keil - Contributions for:   Inconsistent getters in Config #7
 *     Mark Struberg - Contributions for:
 *         move the current source to an api submodule and introduce tck and spec modules #21
 ...

Regardless of any @author tags or who merged a PR.

**Comment by struberg** [comment]
https://en.wikipedia.org/wiki/Threshold_of_originality

**Comment by struberg** [comment]
Or in other words: If I take a Harry Potter book from my daughter and paint a smiley on some random page then I still cannot claim co-authorship of that book.

There is still so much work to do. Please pick any of the parts which are still not done and do some real work on it.

**Comment by keilw** [comment]
Nobody cares about Harry Potter here.
Eclipse has clear IP log practices. Which are not followed if you ignore where the methods came from.
My issue
https://github.com/microprofile/microprofile-config/issues/7
fixed the inconsistency in @Emily-Jiang's  initial codebase from
`<T> Optional<T> getPropertyValue()`
to
`<T> Optional<T> getValue();`

It was not like that before, hence regardless of the hack (should have been a PR in the first place like I did for the wrong headers) that @Emily-Jiang created a PR herself at a time when nobody else pushed, issues that have a structural effect on a piece of code must be acknowledged and are by every proper Eclipse project. 
Also missing from `ConfigSource` btw. 

@Emily-Jiang started with a proper Contributions sector. Something or someone destroyed that along the line, it looked like
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *     Emily Jiang - newly created class
 *******************************************************************************/
initially. 

Like it should.

**Comment by keilw** [comment]
The initial method names had nothing to do with some of the concept studies. Nor was Dmitry's pseudocode in the slides even remotely inspired. 
his `getProperty(String name)` looks like http://docs.spring.io/spring-framework/docs/current/javadoc-api/index.html?org/springframework/context/annotation/PropertySource.html. And so did `<T> Optional<T> getPropertyValue()`. Combining this with aspects by other sources like
` String getString(String path);` in https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/Config.java.

I wonder where "Copycat Rowlings" got the idea to call the API element "Config" instead of "Configuration" in the first place, but Typesafe Config had it like that for a while now :-) 

I asked for a consistent naming in https://github.com/microprofile/microprofile-config/issues/7 of either
getPropertyValue(), getPropertyString() or
getValue(), getString().

The latter was applied.

**Comment by keilw** [comment]
@Emily-Jiang This is not about some author tags or whom to list and whom not, but a proper IP log Eclipse IP team will have a thorough look at like it does for every project and piece of code.
E.g. @rmannibucau or Tomitribe have not contributed to this code so far. He opened https://github.com/microprofile/microprofile-config/issues/13 which is not yet solved. If it was, then e.g. `ConfigProvider` should mention his contribution in the respective section (or "author" tag also works, there is a certain freedom how projects do this) Gerhard Petracek when he spoke about Eclipse once in a different conversation (related to config but before MP) he sounded like he never had anything to do with Eclipse nor intends to. Yet, as he is named contributor to `ConfigSource` Sharon and others in the Eclipse IP team will check for his Eclipse committer ID and if he signed a relevant agreement at least the ECA. Will they find those? If not, the code "he contributed" or all of `ConfigSource` must be removed from this project. There are currently 3 people who contributed to this repository. IBM is clearly fine as Eclipse committer. I am, too. Not sure about  @struberg but let's assume he did sign either an Eclipse Committer Licence Agreement they have on record or ECA he should be OK. And what he contributed is HIS contribution. We don't list Jürgen Höller or authors of https://github.com/typesafehub/config just because you called a method `getString()` like many of their config solutions.

**Comment by struberg** [comment]
Werner, sorry but you have absolutely no clue what you are talking about. 
Romain wrote e.g. the ConfigBuilder in Juy last year, as you can see in the commit logs of my original repo.
https://github.com/struberg/javaConfig/pull/2/commits/0945b23cbf9dadb75fb97551837e6ce3d26496f6#diff-b92d8afc7f270c3893b5d5b40a46a428R1

The point of claiming authorship is NOT whether someone is Eclipse committer or not. The **only** criteria for establishing IP is if someone did own originary work with a substantial level of own invention!
And of course the Eclipse IP council will hopefully check exactly that.

**Comment by keilw** [comment]
Sorry to dissapoint you but I have been working with Eclipse IP team for ages now. And I know what they require. Not sure who, but it seems you made Emily destroy the commit  log for most of those classes. Nobody cares about a single source of inspiration. The classes like `Config` were created as clean-room by Emily, they contain method signatures neither 

/**
     * Return the resolved property value with the specified type for the
     * specified property name
     * 
     * @param <T>
     *             the property type
     * @param propertyName
     *             The configuration propertyName.
     * @param propertyType
     *             The type into which the resolve property value should get converted
     * @return the resolved property value as an Optional of the requested type.
     */
    <T> Optional<T> getValue(String propertyName, Class<T> propertyType);

formerly known as

/**
     * Return the resolved property value with the specified type for the
     * specified property name
     * 
     * @param <T>
     *             the property type
     * @param propertyName
     *             The configuration propertyName.
     * @param propertyType
     *             The type into which the resolve property value should get converted
     * @return the resolved property value as an Optional of the requested type.
     */
    <T> Optional<T> getPropertyValue(String propertyName, Class<T> propertyType);
had not the slightest thing to do with 

 /**
     * Resolves the value configured for the given key and convert it to the required asType.
     *
     * @param key
     * @param asType Also support parameterized Types?
     * @param <T>
     * @return
     * @throws UnsupportedOperationException if there is no {@link Converter} registered for asType
     */
    <T> T getValue(String key, Class<T> asType);
in your July proposal then illegally abusing the "javax." package name space.

They are absolutely different. And I neither looked at nor cared about that stuff when I asked for a consistent method naming in https://github.com/microprofile/microprofile-config/issues/7. 

I don't have to look elsewhere for a `getValue()` method, https://github.com/unitsofmeasurement/unit-api/blob/master/src/main/java/javax/measure/Quantity.java which goes at least as far back as 2005 with https://github.com/unitsofmeasurement/jsr-275/blob/master/src/main/java/javax/measure/quantity/Quantity.java also contains it, so there's not "invention" of having one method called `getValue()` in one place and by coincidence someone else named it the same. 

The contributions log in proper Eclipse projects records that, of course the issue tracker does anyway.

No single line of `Config` was directly derived from that repo you mentioned. 

Having some methods with a similar name is about as related to each other as Dumbledore (for the fans of Harry Potter) to Gandalf, just because both are wizards and wear a grey coat, a long beard and hair ;-)

**Comment by keilw** [comment]
There should be an IP log that acknowleges bugs being fixed, but since the other PR changes the package namespace, this one probably won't be compatible without merge conflicts.

**Pull request closed without merging**
